/**
 * @file dimacs.hpp
 * @brief DIMACS graph I/O — write and read.
 *
 * Provides:
 *   - write_dimacs(os, g, problem = "sp")          Generic DIMACS arc list
 *   - write_dimacs_max_flow(os, g, src, snk, capfn) DIMACS max-flow problem
 *   - read_dimacs(is)                               Parse DIMACS into dimacs_graph
 *
 * The DIMACS family of formats is line oriented; each line begins with a
 * single character describing its kind:
 *
 *   c <comment>                     comment line (ignored)
 *   p <problem> <nodes> <arcs>      problem line (exactly one, first)
 *   n <id> <designation>            node descriptor (e.g. source/sink for max)
 *   a <u> <v> [<weight>]            arc descriptor (1-indexed endpoints)
 *   e <u> <v>                       edge descriptor (clique / coloring format)
 *
 * Vertex ids in DIMACS files are 1-indexed.  The reader normalizes endpoints
 * to 0-indexed ids in the returned structure so they can be used directly
 * with graph-v3 containers.
 *
 * Reference (max-flow): ftp://dimacs.rutgers.edu/pub/netflow/general-info/
 *
 * NOTE: Self-contained — no external dependencies.
 */

#pragma once

#include <graph/graph.hpp>
#include <graph/io/detail/common.hpp>

#include <cstdint>
#include <format>
#include <istream>
#include <ostream>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace graph::io {

// ---------------------------------------------------------------------------
// write_dimacs — generic arc list (shortest-path style: "p sp n m")
// ---------------------------------------------------------------------------

/**
 * @brief Write a graph in generic DIMACS arc-list format.
 *
 * Emits a problem line `p <problem> <n> <m>` followed by one `a u v [w]`
 * line per edge.  Endpoints are written 1-indexed (DIMACS convention).  When
 * the edge value type is formattable it is written as the arc weight.
 *
 * @param os      Output stream.
 * @param g       Graph satisfying adjacency_list.
 * @param problem Problem descriptor placed on the `p` line (e.g. "sp", "max").
 */
template <adj_list::adjacency_list G>
void write_dimacs(std::ostream& os, const G& g, std::string_view problem = "sp") {
  auto n = static_cast<std::uint64_t>(num_vertices(g));

  std::uint64_t m = 0;
  for (auto u : vertices(g)) {
    for (auto uv : edges(g, u)) {
      (void)uv;
      ++m;
    }
  }

  os << "c Generated by graph-v3\n";
  os << "p " << problem << ' ' << n << ' ' << m << '\n';

  for (auto u : vertices(g)) {
    auto uid = static_cast<std::uint64_t>(vertex_id(g, u));
    for (auto uv : edges(g, u)) {
      auto tid = static_cast<std::uint64_t>(target_id(g, uv));
      os << "a " << (uid + 1) << ' ' << (tid + 1);
      if constexpr (detail::has_edge_value<const G>) {
        using EV = std::remove_cvref_t<decltype(graph::edge_value(g, uv))>;
        if constexpr (detail::formattable<EV>) {
          os << ' ' << std::format("{}", graph::edge_value(g, uv));
        }
      }
      os << '\n';
    }
  }
}

// ---------------------------------------------------------------------------
// write_dimacs_max_flow — max-flow problem with source/sink descriptors
// ---------------------------------------------------------------------------

/**
 * @brief Write a graph in DIMACS max-flow format.
 *
 * Emits:
 *   p max <n> <m>
 *   n <source+1> s
 *   n <sink+1>   t
 *   a u v <capacity>   (one per edge)
 *
 * @param os           Output stream.
 * @param g            Graph satisfying adjacency_list.
 * @param source       0-indexed source vertex id.
 * @param sink         0-indexed sink vertex id.
 * @param capacity_fn  Callable (const G&, edge_t<G>) -> capacity value.
 */
template <adj_list::adjacency_list G, class CapacityFn>
void write_dimacs_max_flow(std::ostream& os, const G& g,
                           vertex_id_t<G> source, vertex_id_t<G> sink,
                           CapacityFn capacity_fn) {
  auto n = static_cast<std::uint64_t>(num_vertices(g));

  std::uint64_t m = 0;
  for (auto u : vertices(g)) {
    for (auto uv : edges(g, u)) {
      (void)uv;
      ++m;
    }
  }

  os << "c Generated by graph-v3\n";
  os << "p max " << n << ' ' << m << '\n';
  os << "n " << (static_cast<std::uint64_t>(source) + 1) << " s\n";
  os << "n " << (static_cast<std::uint64_t>(sink) + 1) << " t\n";

  for (auto u : vertices(g)) {
    auto uid = static_cast<std::uint64_t>(vertex_id(g, u));
    for (auto uv : edges(g, u)) {
      auto tid = static_cast<std::uint64_t>(target_id(g, uv));
      os << "a " << (uid + 1) << ' ' << (tid + 1) << ' '
         << std::format("{}", capacity_fn(g, uv)) << '\n';
    }
  }
}

// ---------------------------------------------------------------------------
// read_dimacs — parser
// ---------------------------------------------------------------------------

/// A single parsed DIMACS arc/edge (endpoints normalized to 0-indexed).
struct dimacs_edge {
  std::uint64_t source{0};
  std::uint64_t target{0};
  std::string   weight; ///< Arc weight/capacity as text (empty if none)
};

/// A parsed DIMACS node descriptor (id normalized to 0-indexed).
struct dimacs_node {
  std::uint64_t id{0};
  std::string   designation; ///< e.g. "s" (source) or "t" (sink)
};

/// Parsed DIMACS graph.
struct dimacs_graph {
  std::string              problem;          ///< Problem type from the `p` line
  std::uint64_t            num_vertices{0};  ///< Declared vertex count
  std::uint64_t            num_arcs{0};      ///< Declared arc/edge count
  std::vector<dimacs_node> nodes;            ///< Node descriptors (`n` lines)
  std::vector<dimacs_edge> edges;            ///< Arc/edge descriptors
};

/**
 * @brief Parse a DIMACS file (max-flow, shortest-path, or edge format).
 *
 * Recognizes `c`, `p`, `n`, `a`, and `e` line kinds.  Endpoints are converted
 * from the file's 1-indexed convention to 0-indexed ids.  Unknown line kinds
 * are ignored.
 *
 * @param is Input stream containing DIMACS text.
 * @return Parsed dimacs_graph.
 */
inline dimacs_graph read_dimacs(std::istream& is) {
  dimacs_graph result;
  std::string  line;

  while (std::getline(is, line)) {
    std::istringstream ls(line);
    char               kind = 0;
    if (!(ls >> kind)) continue; // blank line

    switch (kind) {
      case 'c':
        break; // comment
      case 'p': {
        ls >> result.problem >> result.num_vertices >> result.num_arcs;
        break;
      }
      case 'n': {
        std::uint64_t id = 0;
        std::string   designation;
        ls >> id >> designation;
        result.nodes.push_back({id > 0 ? id - 1 : 0, std::move(designation)});
        break;
      }
      case 'a':
      case 'e': {
        std::uint64_t u = 0, v = 0;
        ls >> u >> v;
        std::string weight;
        ls >> weight; // optional; empty if absent
        result.edges.push_back({u > 0 ? u - 1 : 0, v > 0 ? v - 1 : 0, std::move(weight)});
        break;
      }
      default:
        break; // ignore unknown line kinds
    }
  }

  return result;
}

} // namespace graph::io
