/**
 * @file metis.hpp
 * @brief METIS graph I/O — write and read.
 *
 * Provides:
 *   - write_metis(os, g)        Emit a graph in METIS adjacency format
 *   - read_metis(is)            Parse a METIS file into metis_graph
 *
 * The METIS graph format describes an *undirected* graph:
 *
 *   % comment line (ignored)
 *   <n> <m> [fmt] [ncon]                 header: vertices, edges, format flags
 *   <adjacency of vertex 1>              one line per vertex (1-indexed)
 *   <adjacency of vertex 2>
 *   ...
 *
 * `m` counts each undirected edge once.  The optional 3-digit `fmt` flag
 * encodes whether vertex sizes / vertex weights / edge weights are present
 * (hundreds = vertex sizes, tens = vertex weights, ones = edge weights).
 * When edge weights are present, each neighbour is followed by its weight.
 *
 * The writer treats the input graph as undirected: each edge (u,v) contributes
 * v to u's list and u to v's list, deduplicated, so the output is symmetric.
 * The reader normalizes neighbour ids from the file's 1-indexed convention to
 * 0-indexed ids.
 *
 * Reference: METIS manual, "Graph Input File" section.
 *
 * NOTE: Self-contained — no external dependencies.
 */

#pragma once

#include <graph/graph.hpp>
#include <graph/io/detail/common.hpp>

#include <cstdint>
#include <format>
#include <istream>
#include <ostream>
#include <set>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

namespace graph::io {

// ---------------------------------------------------------------------------
// write_metis
// ---------------------------------------------------------------------------

/**
 * @brief Write a graph in METIS adjacency format (treated as undirected).
 *
 * Builds a symmetric adjacency: every edge (u,v) lists v under u and u under v
 * (deduplicated, no self-loops).  Vertex ids are written 1-indexed.  When
 * @p with_weights is true and the edge value type is formattable, each
 * neighbour is followed by its weight and the `fmt` header flag is set to 001.
 *
 * @param os           Output stream.
 * @param g            Graph satisfying adjacency_list.
 * @param with_weights Emit edge weights (requires a formattable edge value).
 */
template <adj_list::adjacency_list G>
void write_metis(std::ostream& os, const G& g, bool with_weights = false) {
  const auto n = static_cast<std::size_t>(num_vertices(g));

  // Build symmetric, deduplicated adjacency. Store (neighbour, weight-text).
  std::vector<std::vector<std::pair<std::uint64_t, std::string>>> adj(n);
  std::vector<std::set<std::uint64_t>>                            seen(n);

  bool emit_weights = false;
  if constexpr (detail::has_edge_value<const G>) {
    using EV = std::remove_cvref_t<decltype(graph::edge_value(g, std::declval<edge_t<G>>()))>;
    emit_weights = with_weights && detail::formattable<EV>;
  }

  auto add = [&](std::uint64_t a, std::uint64_t b, const std::string& w) {
    if (a == b) return;                 // skip self-loops (invalid in METIS)
    if (a >= n) return;
    if (seen[a].insert(b).second) adj[a].push_back({b, w});
  };

  for (auto u : vertices(g)) {
    auto uid = static_cast<std::uint64_t>(vertex_id(g, u));
    for (auto uv : edges(g, u)) {
      auto tid = static_cast<std::uint64_t>(target_id(g, uv));
      std::string w;
      if constexpr (detail::has_edge_value<const G>) {
        using EV = std::remove_cvref_t<decltype(graph::edge_value(g, uv))>;
        if constexpr (detail::formattable<EV>) {
          if (emit_weights) w = std::format("{}", graph::edge_value(g, uv));
        }
      }
      add(uid, tid, w);
      add(tid, uid, w);
    }
  }

  std::uint64_t edge_count = 0;
  for (const auto& a : adj) edge_count += a.size();
  edge_count /= 2; // each undirected edge counted twice

  os << "% Generated by graph-v3\n";
  os << n << ' ' << edge_count;
  if (emit_weights) os << " 001";
  os << '\n';

  for (std::size_t i = 0; i < n; ++i) {
    bool first = true;
    for (const auto& [nbr, w] : adj[i]) {
      if (!first) os << ' ';
      first = false;
      os << (nbr + 1); // 1-indexed
      if (emit_weights) os << ' ' << (w.empty() ? std::string("1") : w);
    }
    os << '\n';
  }
}

// ---------------------------------------------------------------------------
// read_metis
// ---------------------------------------------------------------------------

/// A single METIS adjacency entry (neighbour normalized to 0-indexed).
struct metis_adjacency {
  std::uint64_t neighbor{0};
  std::string   weight; ///< Edge weight as text (empty if format has none)
};

/// Parsed METIS graph.
struct metis_graph {
  std::uint64_t num_vertices{0}; ///< Declared vertex count
  std::uint64_t num_edges{0};    ///< Declared (undirected) edge count
  int           fmt{0};          ///< Format flag from the header (0 if absent)
  int           ncon{0};         ///< Number of vertex weights (0 if absent)
  /// adjacency[i] holds the neighbours of vertex i (0-indexed).
  std::vector<std::vector<metis_adjacency>> adjacency;
  /// vertex_weights[i] holds the weights of vertex i (empty if none).
  std::vector<std::vector<std::uint64_t>> vertex_weights;
};

/**
 * @brief Parse a METIS graph file into a metis_graph structure.
 *
 * Handles the optional 3-digit `fmt` flag (vertex sizes / vertex weights /
 * edge weights) and the optional `ncon` field.  Lines beginning with `%` are
 * comments.  Neighbour ids are converted from 1-indexed to 0-indexed.
 *
 * @param is Input stream containing METIS text.
 * @return Parsed metis_graph.
 */
inline metis_graph read_metis(std::istream& is) {
  metis_graph result;
  std::string line;

  auto next_data_line = [&](std::string& out) -> bool {
    while (std::getline(is, out)) {
      auto first = out.find_first_not_of(" \t\r");
      if (first == std::string::npos) continue; // blank
      if (out[first] == '%') continue;          // comment
      return true;
    }
    return false;
  };

  // Header line.
  if (!next_data_line(line)) return result;
  {
    std::istringstream hs(line);
    hs >> result.num_vertices >> result.num_edges;
    hs >> result.fmt;  // optional
    hs >> result.ncon; // optional
  }

  const bool has_vertex_sizes  = (result.fmt / 100) % 10 != 0;
  const bool has_vertex_weight = (result.fmt / 10) % 10 != 0;
  const bool has_edge_weight   = (result.fmt % 10) != 0;
  const int  ncon              = result.ncon > 0 ? result.ncon : (has_vertex_weight ? 1 : 0);

  result.adjacency.resize(result.num_vertices);
  result.vertex_weights.resize(result.num_vertices);

  for (std::uint64_t i = 0; i < result.num_vertices; ++i) {
    if (!next_data_line(line)) break;
    std::istringstream ls(line);

    if (has_vertex_sizes) {
      std::uint64_t vsize = 0;
      ls >> vsize; // consume and discard vertex size
    }
    for (int c = 0; c < ncon; ++c) {
      std::uint64_t vw = 0;
      if (ls >> vw) result.vertex_weights[i].push_back(vw);
    }

    std::uint64_t nbr = 0;
    while (ls >> nbr) {
      metis_adjacency entry;
      entry.neighbor = nbr > 0 ? nbr - 1 : 0;
      if (has_edge_weight) {
        std::string w;
        ls >> w;
        entry.weight = std::move(w);
      }
      result.adjacency[i].push_back(std::move(entry));
    }
  }

  return result;
}

} // namespace graph::io
